# Generated by Django 3.1.2 on 2020-12-24 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import message.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to=message.models.customer_image_file_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('tag', models.CharField(choices=[('message', 'message'), ('issue', 'issue')], default='message', max_length=15)),
                ('status', models.CharField(choices=[('done', 'done'), ('working_on', 'working_on'), ('on_hold', 'on_hold')], default='working_on', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
