# Generated by Django 3.1.2 on 2020-12-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_mesage_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesage',
            options={'ordering': ['-timestamp', '-created_at']},
        ),
        migrations.RenameField(
            model_name='mesage',
            old_name='user',
            new_name='author',
        ),
    ]
