# Generated by Django 3.1.2 on 2020-12-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20201224_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesage',
            old_name='author',
            new_name='user',
        ),
    ]
