# Generated by Django 3.1.2 on 2020-12-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20201224_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesage',
            old_name='user',
            new_name='author',
        ),
    ]
