# Generated by Django 3.1.2 on 2020-12-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20201226_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
