# Generated by Django 3.1.2 on 2020-12-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesage',
            options={'ordering': ['-timestamp', '-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelTable(
            name='mesage',
            table='messages',
        ),
    ]
