# Generated by Django 3.1.5 on 2021-02-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210201_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_cart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
