# Generated by Django 3.1.5 on 2021-02-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_user_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_cart_id',
        ),
    ]
