# Generated by Django 3.1.7 on 2021-02-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_subscription_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='mail_message',
            new_name='mailchimp_message',
        ),
    ]
