# Generated by Django 3.1.5 on 2021-02-07 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210207_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
