# Generated by Django 3.1.5 on 2021-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_billing_is_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_is_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
