# Generated by Django 3.1.2 on 2020-12-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20201226_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
