# Generated by Django 3.1.2 on 2020-12-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='object_pk',
        ),
    ]
