version: "3.8"

services:
  nginx:
    build: ./nginx
    volumes:
      - ./core/static:/static
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build: .
    command: gunicorn core.wsgi:application -b 0.0.0.0:8000 --log-level=debug
    volumes:
      - ./core:/opt/app
    ports:
      - "8000:8000"
    env_file:
      - environment
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - my-pg-data-1:/var/lib/postgresql/data/
    env_file:
      - environment
    restart: always

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core worker -l INFO -E
    volumes:
      - ./core:/opt/app
    env_file:
      - environment
    restart: always
    depends_on:
      - redis
      - django

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    env_file:
      - environment

volumes:
  my-pg-data-1:
    driver: local
