# Generated by Django 3.1.5 on 2021-02-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingaddress'),
        ('order', '0002_order_billing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='billing.billingprofile'),
        ),
    ]
