# Generated by Django 3.1.2 on 2020-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201001_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], max_length=32),
        ),
    ]
