# Generated by Django 3.1.2 on 2020-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201001_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
