# Generated by Django 3.1.2 on 2021-01-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='user',
            new_name='author',
        ),
    ]
