# Generated by Django 3.1.5 on 2021-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20210207_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='billing_is_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
