# Generated by Django 3.1.5 on 2021-02-08 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingaddress_billing_is_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='billing_is_shipping',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
