# Generated by Django 3.1.5 on 2021-02-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20210208_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address_1',
            new_name='address_1_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address_2',
            new_name='address_2_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='city',
            new_name='city_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='country',
            new_name='country_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='postalcode',
            new_name='postcode_b',
        ),
    ]
