# Generated by Django 3.1.5 on 2021-02-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20210208_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='costumer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
