# Generated by Django 3.1.4 on 2020-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
