# Generated by Django 3.1.4 on 2020-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_voting_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
