# Generated by Django 3.1.4 on 2020-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_auto_20201220_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='counter',
            new_name='counter_negative',
        ),
        migrations.AddField(
            model_name='voting',
            name='counter_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='counter_positive',
            field=models.IntegerField(default=0),
        ),
    ]
