# Generated by Django 3.1.2 on 2020-12-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_auto_20201220_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='created_by',
            new_name='user',
        ),
    ]
