# Generated by Django 3.1.2 on 2020-12-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0007_auto_20201222_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingchoices',
            options={'verbose_name': 'votingchoses'},
        ),
    ]
