# Generated by Django 3.1.2 on 2020-12-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0009_auto_20201222_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'voting', 'verbose_name_plural': 'voting_s'},
        ),
        migrations.AlterModelOptions(
            name='votingchoices',
            options={'verbose_name': 'voting_choice', 'verbose_name_plural': 'voting_choices'},
        ),
        migrations.AlterModelTable(
            name='voting',
            table='voting',
        ),
        migrations.AlterModelTable(
            name='votingchoices',
            table='voting_choice',
        ),
    ]
